Badger-Finance/badger-rewards

rewards/aws/helpers.py
subgraph/subgraph_utils.py

Reverts Badger-Finance/badger-rewards#48

Revert "S3 fix"

---

rewards/aws/helpers.py

Reverts Badger-Finance/badger-rewards#47

Revert "handle s3 local"

---

helpers/constants.py
rewards/classes/RewardsManager.py
rewards/snapshot/chain_snapshot.py

Add separate blacklists for emissions ( badger + digg) and yield tokens ( bcvx + bcxvcrv )

feat: refactor blacklist for yield token distribution

---

rewards/calc_rewards.py
rewards/classes/TreeManager.py
rewards/rewards_checker.py
subgraph/queries/harvests.py

Use correct client name when fetching sushi harvests

feat: black formatting and fix sushi harvests

---

helpers/constants.py
helpers/enums.py
rewards/aws/boost.py
rewards/aws/trees.py
rewards/boost/boost_utils.py
rewards/snapshot/claims_snapshot.py
tests/test_boost.py

prod bots only upload boost to prod bucket, staging bots only upload boost to staging buckets

feat: boost only uploads to environment bucket, tests

---

config/env_config.py
helpers/constants.py
rewards/aws/boost.py
rewards/calc_rewards.py
rewards/classes/RewardsManager.py
rewards/explorer.py
rewards/tx_utils.py
scripts/rewards/eth/retroactive/fix_eth_rewards/fix_eth_rewards_approve.py
scripts/rewards/eth/retroactive/retro_eth_approve.py
tests/cycle_utils.py
tests/test_cycles_arb.py
tests/test_cycles_eth.py
tests/test_cycles_poly.py
tests/utils.py

Notes:
- refactored add_multipliers, pulled downloading and uploading boost file out to make testing easier and remove side effects
- arbitrum tests won't work right now, fork broken for arb network
- marked tests requiring specific network, poly won't run as part of gha hook
- sometimes subgraph throws 500 errors and causes tests to fail, maybe should not be included as part of unit tests? more integration

Brownie test cycles

---

.deploy/base/propose_eth_cycle_bot.yaml
rewards/calc_rewards.py
rewards/classes/RewardsList.py

- no longer save on propose
- remove custom upload_tree code
- return eth cycles to usual cadence
- enable boost bot

chore: remove debugging code now that cycles stable

---

config/env_config.py
rewards/aws/trees.py
rewards/classes/MerkleTree.py
rewards/classes/RewardsList.py
rewards/classes/TreeManager.py
rewards/snapshot/token_snapshot.py
rewards/utils/rewards_utils.py
rewards/utils/tree_utils.py
rewards_tests/test_polygon.py
rewards_tests/test_propose_approve_rewards.py
subgraph/queries/tokens.py
tests/test_boost.py
tests/test_claimable.py

**Done:**
1. Add __init__.py files to all python modules. Closes #370 
2. Remove all commented code from the project. Closes #286 
3. Removes some unused code, like `rewards_tests` module. Closes #371 
4. Also fix `fetch_token_balances` function by adding chain param to it

Improvements

---

.gitignore
docker-compose.yaml
scripts/rewards/eth/approve_eth.py
scripts/rewards/eth/auto_approve_eth.py

- Add secrets/ folder to git ignore to have local storage of sensitive files
- modifications of scripts to run the correct docker scripts and pull correct config

Docker update

---

.coveragerc

Changes:
- Omit testing folders from codecov checks

chore: omit tests from codecov

---

helpers/constants.py
rewards/utils/tx_utils.py
subgraph/queries/tokens.py
tests/test_rewards_manager.py
tests/test_tree_utils.py
tests/test_tx_utils.py

**Done:**
1. Add `DECIMAL_MAPPING` to be used everywhere instead of `10 ** 18`
2. Some refactorings in methods from `tx_utils.py`: added return parameters, removed some obvious bugs
3. Imrove test coverage for `tx_utils.py`
Fixes #200

Add DECIMAL_MAPPING constant to be used

---

tests/conftest.py
tests/test_utils/test_http_requests_functions.py

As we have now problems with cached data, it was decided to clear cache for each test function we have

Add clear_cache fixture to clear cache for fetch token names and prices

---

helpers/constants.py

Policy updates: https://github.com/Badger-Finance/badger-IaC/pull/69
Issue: https://github.com/Badger-Finance/badger-rewards/issues/254

chore: send staging boost logs to staging webhooks

---

rewards/boost/boost_utils.py
rewards/boost/calc_boost.py
tests/test_boost/test_calc_boost.py

Splitting `badger_boost` function into smaller functions for better testability and readability
Fixes #413

chore: refactor calc_boost to smaller functions

---

.deploy/base/propose_eth_cycle_bot.yaml
scripts/rewards/fix_eth_rewards/fix.py

Quick normal cycle to have correct multipliers on files

fix: run quick normal cycle

---

rewards/aws/helpers.py
rewards/calc_rewards.py
rewards/classes/RewardsList.py
rewards/classes/RewardsManager.py
rewards/dynamo_handlers.py
rewards/utils/token_utils.py
tests/test_calc_rewards.py
tests/test_claimable.py
tests/test_dynamo_handlers.py
tests/test_managers/test_rewards_manager.py

1. Add `put_rewards_data` dynamo handler
2. Use handler in `approve_root` in case of `success=True`
3. Many tests for all tastes
Also, minor fixes and cleanups
Fixes #387

Feature: Store sett rewards to dynamo table

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_stg.yaml

HAL-04 - CICD - LACK OF CONTAINER SCANNING

chore: scan containers for vulns before publish

---

rewards/feature_flags/__init__.py
rewards/feature_flags/feature_flags.py
tests/test_feature_flags.py

Adds `FeatureFlags` class.
Closes #626

Feature flags

---

integration_tests/test_boost_workflow.py

chore: mock dynamodb calls in integration test

---

subgraph/queries/tokens.py
tests/test_subgraph/test_data.py
tests/test_subgraph/test_tokens.py

Increase coverage for token queries
Fixes #397

chore: Tokens query gql coverage

---

rewards/aws/trees.py
rewards/rewards_checker.py
tests/test_aws.py
tests/test_utils/test_rewards_utils.py

chore: More coverage for reward utils and aws module

---

rewards/boost/calc_boost.py
tests/test_boost/test_calc_boost.py

chore: refactor bvecvx alloc func

---

rewards/utils/rewards_utils.py
tests/conftest.py
tests/test_boost/test_calc_boost.py
tests/test_emission_handlers.py
tests/test_managers/test_rewards_manager.py
tests/test_snapshots/test_claims_snapshot.py
tests/test_utils/test_boost_utils.py
tests/test_utils/test_rewards_utils.py

Fix external api calls

---

.deploy/base/approve_poly_cycle_bot.yaml
.deploy/base/propose_poly_cycle_bot.yaml
Dockerfile
rewards/snapshot/token_snapshot.py

Rewards aren't being distributed on polygon, pause to prevent issues.

chore: pause polygon

---

subgraph/config.py

chore: migrate to badger subgraphs

---

.deploy/base/propose_eth_cycle_bot.yaml
scripts/rewards/redirect_rewards/approve.py
scripts/rewards/redirect_rewards/propose.py
scripts/rewards/redirect_rewards/redirect_rewards.py

feat: Redirect rewards from voter msig to Trops

---

.deploy/base/propose_eth_cycle_bot.yaml

This reverts commit 68ca74ab1e2d6aec5dc058616ca3555d8a6f1feb.

Revert "chore: fix cycle"

---

.deploy/base/propose_eth_cycle_bot.yaml

This reverts commit 624ff91d385cee862cec457883795883c36804cc.

Revert "fix cycle 11-7"

---

.deploy/base/approve_arb_cycle_bot.yaml
.deploy/base/arb_boost_bot.yaml
.deploy/base/propose_arb_cycle_bot.yaml

feat: sunset arbitrum completely

---

.deploy/base/propose_eth_cycle_bot.yaml

This reverts commit c67f3e465f2bf57dbacde0f31480905b94c32b49.

Revert "fix: fix cycle 5-27"

---

.deploy/base/propose_eth_cycle_bot.yaml

This reverts commit 8b2f214d284d26360e3803c9bf87063ec76e9132.

Revert "fix: fix cycle 5-28"
